
services:
  postgres:
    image: postgres:16-alpine
    container_name: report-service-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "StrongPassword123!"
      POSTGRES_DB: report_services
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: report-service-dbeaver
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: report-service-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "StrongPassword123!"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_LOGIN_BANNER: '"Report Services - PostgreSQL Admin"'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  cloudbeaver_workspace:
  pgadmin_data: