services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: report-service-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: report-service-dbeaver
    restart: unless-stopped
    depends_on:
      - sqlserver
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace

volumes:
  sqlserver_data:
  cloudbeaver_workspace:
